- alias: Direct inconsistency turn on
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: "on"
  action:
    - service: light.turn_on
      target:
        entity_id: light.kitchen

- alias: Direct inconsistency turn off
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: "on"
  action:
    - service: light.turn_off
      target:
        entity_id: light.kitchen
