- alias: Redundant porch light A
  trigger:
    - platform: state
      entity_id: binary_sensor.porch_motion
      to: "on"
  action:
    - service: light.turn_on
      target:
        entity_id: light.porch

- alias: Redundant porch light B
  trigger:
    - platform: state
      entity_id: binary_sensor.porch_motion
      to: "on"
  action:
    - service: light.turn_on
      target:
        entity_id: light.porch
