- alias: Indirect start fan
  trigger:
    - platform: state
      entity_id: binary_sensor.bath_motion
      to: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.bath_fan

- alias: Indirect stop fan after fan turns on
  trigger:
    - platform: state
      entity_id: switch.bath_fan
      to: "on"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.bath_fan
