# fetch_HA.py
# ------------------------------------------------------------
# Fetches Home Assistant /api/states using HA_BASE_URL + HA_TOKEN
# and generates src/data/entities_homeassistant.js
# ------------------------------------------------------------

import json
import os
from typing import Any, Dict, List
from urllib.request import Request, urlopen
from urllib.error import URLError, HTTPError

from dotenv import load_dotenv

load_dotenv()

HA_BASE_URL = os.getenv("HA_BASE_URL")  # e.g. http://192.168.1.100:8123
HA_TOKEN = os.getenv("HA_TOKEN")

if not HA_BASE_URL or not HA_TOKEN:
    raise RuntimeError("HA_BASE_URL 또는 HA_TOKEN이 .env에 설정되지 않았습니다.")

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_ENTITIES_JS = os.path.join(HERE, "entities_homeassistant.js")

# ------------------------------------------------------------
# Filtering policy (Blockly에 보여줄 기본 도메인들)
# ------------------------------------------------------------
ALLOW_DOMAINS = {
    "light",
    "switch",
    "fan",
    "lock",
    "cover",
    "media_player",
    "climate",
    "camera",
    "sensor",
    "binary_sensor",
    "input_boolean",
    "person",
    "sun",
    "automation",
}

DENY_DOMAINS = {
    "update",
    "conversation",
    "event",
    "todo",
    "zone",
    "tts",
    "weather",
}


def safe_domain(entity_id: str) -> str:
    if not entity_id or "." not in entity_id:
        return ""
    return entity_id.split(".", 1)[0].strip()


def simple_name(entity: Dict[str, Any]) -> str:
    attrs = entity.get("attributes") or {}
    return attrs.get("friendly_name") or entity.get("entity_id") or ""


def slim_attributes(attrs: Dict[str, Any]) -> Dict[str, Any]:
    if not isinstance(attrs, dict):
        return {}

    keep_keys = [
        "friendly_name",
        "device_class",
        "unit_of_measurement",
        "supported_features",
        "supported_color_modes",
        "color_mode",
        "assumed_state",
        "options",
    ]
    out = {}
    for k in keep_keys:
        if k in attrs:
            out[k] = attrs[k]
    return out


def should_include(domain: str) -> bool:
    if not domain:
        return False
    if domain in DENY_DOMAINS:
        return False
    if domain in ALLOW_DOMAINS:
        return True
    return False


def fetch_states() -> List[Dict[str, Any]]:
    url = HA_BASE_URL.rstrip("/") + "/api/states"
    req = Request(url)
    req.add_header("Authorization", f"Bearer {HA_TOKEN}")
    req.add_header("Content-Type", "application/json")

    try:
        with urlopen(req, timeout=30) as resp:
            raw = resp.read().decode("utf-8")
    except HTTPError as e:
        raise RuntimeError(f"HTTP error: {e.code} {e.reason}") from e
    except URLError as e:
        raise RuntimeError(f"Network error: {e.reason}") from e

    data = json.loads(raw)
    if not isinstance(data, list):
        raise ValueError("API response must be a list (Home Assistant /api/states).")
    return data


def build_entities(raw: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []

    for e in raw:
        entity_id = e.get("entity_id", "")
        domain = safe_domain(entity_id)
        if not should_include(domain):
            continue

        attrs = e.get("attributes") or {}
        item = {
            "entity_id": entity_id,
            "domain": domain,
            "name": simple_name(e),
            "state": e.get("state"),
            "attributes": slim_attributes(attrs),
        }
        out.append(item)

    out.sort(key=lambda x: (x.get("domain", ""), x.get("entity_id", "")))
    return out


def write_entities_js(path: str, entities: List[Dict[str, Any]]) -> None:
    content = (
        "// AUTO-GENERATED by fetch_HA.py\n"
        "// Source: Home Assistant /api/states\n\n"
        "export const dummyEntities = "
        + json.dumps(entities, ensure_ascii=False, indent=2)
        + ";\n\n"
        "export const notifyDevices = [];\n"
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def main():
    raw = fetch_states()
    entities = build_entities(raw)
    write_entities_js(OUT_ENTITIES_JS, entities)
    print(f"Wrote {OUT_ENTITIES_JS} with {len(entities)} entities")


if __name__ == "__main__":
    main()
