# filter_entities.py
# ------------------------------------------------------------
# Reads Home Assistant "get_states" dump JSON (test_entities.json)
# and generates:
#   - src/data/test2_entities.js
#   - src/data/test2_options.js
#
# Safe: does NOT touch existing entities.js / options.js
# ------------------------------------------------------------

import json
import os
from typing import Any, Dict, List

# ------------------------------------------------------------
# Paths (default: run this script from anywhere)
# ------------------------------------------------------------

HERE = os.path.dirname(os.path.abspath(__file__))

# 프로젝트 구조가 보통:
# HA_smartblock/
#   src/
#     data/
#     utils/   <-- (여기서 filter_entities.py 실행한다고 가정)
#
# 입력: src/data/test_entities.json
DATA_DIR = os.path.normpath(os.path.join(HERE, "..", "data"))
IN_JSON = os.path.join(DATA_DIR, "test_entities.json")

OUT_ENTITIES_JS = os.path.join(DATA_DIR, "test2_entities.js")
OUT_OPTIONS_JS = os.path.join(DATA_DIR, "test2_options.js")

# ------------------------------------------------------------
# Filtering policy (Blockly에 보여줄 기본 도메인들)
# 필요하면 여기만 추가/삭제하면 됨
# ------------------------------------------------------------
ALLOW_DOMAINS = {
    "light",
    "switch",
    "fan",
    "lock",
    "cover",
    "media_player",
    "climate",
    "camera",
    "sensor",
    "binary_sensor",
    "input_boolean",
    "person",
    "sun",
    "automation",  # 디버깅/테스트할 때 유용 (싫으면 빼도 됨)
}

# 제외하고 싶은 시스템성 도메인(원하면 여기 추가)
DENY_DOMAINS = {
    "update",
    "conversation",
    "event",
    "todo",
    "zone",
    "tts",
    "weather",
}

# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------

def safe_domain(entity_id: str) -> str:
    if not entity_id or "." not in entity_id:
        return ""
    return entity_id.split(".", 1)[0].strip()

def simple_name(entity: Dict[str, Any]) -> str:
    attrs = entity.get("attributes") or {}
    return attrs.get("friendly_name") or entity.get("entity_id") or ""

def slim_attributes(attrs: Dict[str, Any]) -> Dict[str, Any]:
    """너무 무거워지지 않게 자동화/블록 UI에 쓸만한 것만 남김.
    (원하면 그냥 attrs 전체를 반환해도 됨)
    """
    if not isinstance(attrs, dict):
        return {}

    keep_keys = [
        "friendly_name",
        "device_class",
        "unit_of_measurement",
        "supported_features",
        "supported_color_modes",
        "color_mode",
        "assumed_state",
        "options",
    ]
    out = {}
    for k in keep_keys:
        if k in attrs:
            out[k] = attrs[k]
    return out

def should_include(domain: str) -> bool:
    if not domain:
        return False
    if domain in DENY_DOMAINS:
        return False
    if domain in ALLOW_DOMAINS:
        return True
    return False

def js_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("`", "\\`")

# ------------------------------------------------------------
# Load
# ------------------------------------------------------------

def load_states(path: str) -> List[Dict[str, Any]]:
    if not os.path.exists(path):
        raise FileNotFoundError(f"Input JSON not found: {path}")

    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, list):
        raise ValueError("Input JSON must be a list (Home Assistant get_states result).")

    return data

# ------------------------------------------------------------
# Build output data
# ------------------------------------------------------------

def build_entities(raw: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []

    for e in raw:
        entity_id = e.get("entity_id", "")
        domain = safe_domain(entity_id)

        if not should_include(domain):
            continue

        attrs = e.get("attributes") or {}
        item = {
            "entity_id": entity_id,
            "domain": domain,
            "name": simple_name(e),
            "state": e.get("state"),
            "attributes": slim_attributes(attrs),
        }
        out.append(item)

    # 정렬: domain -> entity_id
    out.sort(key=lambda x: (x.get("domain", ""), x.get("entity_id", "")))
    return out

# get_states만으론 notify 디바이스 목록이 안 나오는 경우가 많아서
# 일단 빈 배열로 두고, 나중에 get_services까지 붙이면 자동 생성 가능.
def build_notify_devices(_: List[Dict[str, Any]]) -> List[str]:
    return []

# ------------------------------------------------------------
# Generate JS files
# ------------------------------------------------------------

def write_test2_entities_js(path: str, entities: List[Dict[str, Any]], notify_devices: List[str]) -> None:
    payload = {
        "dummyEntities": entities,
        "notifyDevices": notify_devices,
    }

    # JS 모듈로 export
    content = (
        "// AUTO-GENERATED by filter_entities.py\n"
        "// Input : test_entities.json (HA get_states raw dump)\n"
        "// Output: test2_entities.js (safe test file)\n\n"
        "export const dummyEntities = "
        + json.dumps(payload["dummyEntities"], ensure_ascii=False, indent=2)
        + ";\n\n"
        "export const notifyDevices = "
        + json.dumps(payload["notifyDevices"], ensure_ascii=False, indent=2)
        + ";\n"
    )

    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

def write_test2_options_js(path: str) -> None:
    # 네가 준 options.js를 거의 그대로 복사하되,
    # import 경로만 test2_entities.js로 바꾼 "테스트용 options" 생성
    content = """// AUTO-GENERATED by filter_entities.py
// Safe test copy of options.js
// It imports entities from './test2_entities.js'

import { dummyEntities, notifyDevices } from './test2_entities.js';

/* ============================================================
 * DOMAIN SPEC (actions / states)
 * ============================================================ */

export const DOMAIN_SPEC = {
  light: {
    actions: [
      ['on', 'turn_on'],
      ['off', 'turn_off'],
    ],
    states: [
      ['on', 'on'],
      ['off', 'off'],
    ],
  },

  switch: {
    actions: [
      ['on', 'turn_on'],
      ['off', 'turn_off'],
    ],
    states: [
      ['on', 'on'],
      ['off', 'off'],
    ],
  },

  lock: {
    actions: [
      ['lock', 'lock'],
      ['unlock', 'unlock'],
    ],
    states: [
      ['locked', 'locked'],
      ['unlocked', 'unlocked'],
    ],
  },

  media_player: {
    actions: [
      ['play', 'media_play'],
      ['pause', 'media_pause'],
      ['stop', 'media_stop'],
      ['next', 'media_next_track'],
      ['previous', 'media_previous_track'],
      ['volume up', 'volume_up'],
      ['volume down', 'volume_down'],
    ],
    states: [
      ['playing', 'playing'],
      ['paused', 'paused'],
      ['idle', 'idle'],
      ['standby', 'standby'],
      ['off', 'off'],
    ],
  },

  climate: {
    actions: [
      ['on', 'turn_on'],
      ['off', 'turn_off'],
      ['set temperature', 'set_temperature'],
    ],
    states: [
      ['heat', 'heat'],
      ['cool', 'cool'],
      ['auto', 'auto'],
      ['off', 'off'],
    ],
  },

  cover: {
    actions: [
      ['open', 'open_cover'],
      ['close', 'close_cover'],
      ['stop', 'stop_cover'],
    ],
    states: [
      ['open', 'open'],
      ['closed', 'closed'],
      ['opening', 'opening'],
      ['closing', 'closing'],
      ['stopped', 'stopped'],
    ],
  },

  binary_sensor: {
    states: [
      ['on', 'on'],
      ['off', 'off'],
    ],
  },

  input_boolean: {
    states: [
      ['on', 'on'],
      ['off', 'off'],
    ],
  },
  sun: {
    states: [
      ['above horizon', 'above_horizon'],
      ['below horizon', 'below_horizon'],
    ],
  },
};

/* ============================================================
 * DOMAIN FILTER HELPERS
 * ============================================================ */

export const ACTION_DOMAINS = Object.entries(DOMAIN_SPEC)
  .filter(([, spec]) => Array.isArray(spec.actions) && spec.actions.length > 0)
  .map(([domain]) => domain);

export const STATE_DOMAINS = Object.entries(DOMAIN_SPEC)
  .filter(([, spec]) => Array.isArray(spec.states) && spec.states.length > 0)
  .map(([domain]) => domain);

export function getActions(domain) {
  const opts = DOMAIN_SPEC[domain]?.actions;
  return Array.isArray(opts) && opts.length ? opts : [['(No actions)', '']];
}

export function getStates(domain) {
  const opts = DOMAIN_SPEC[domain]?.states;
  return Array.isArray(opts) && opts.length ? opts : [['(No states)', '']];
}

/* ============================================================
 * CONDITION / EVENT OPTIONS
 * ============================================================ */

export const NUMERIC_OPERATORS = [
  ['>', '>'],
  ['≥', '>='],
  ['<', '<'],
  ['≤', '<='],
  ['==', '=='],
];

export const STATE_COMPARATORS = [
  ['is', 'is'],
  ['is_not', 'is_not'],
];

export const EVENT_TYPES = [
  ['state', 'state'],
];

/* ============================================================
 * CAMERA ENTITY OPTIONS (notify tag 용)
 * ============================================================ */

export const getCameraEntityOptions = () => {
  const cams = (dummyEntities || []).filter(
    (e) => (e.entity_id || '').startsWith('camera.')
  );

  if (!cams.length) return [['(no camera)', '']];

  return cams.map((e) => [
    e.attributes?.friendly_name || e.entity_id,
    e.entity_id,
  ]);
};

/* ============================================================
 * NOTIFY OPTIONS
 * ============================================================ */

export const slug = (s) =>
  String(s || '')
    .trim()
    .toLowerCase()
    .replace(/\\s+/g, '_')
    .replace(/[^a-z0-9_]+/g, '');

export const CUSTOM_NOTIFY_TARGETS = [
  'USER1_devices',
  'USER2_devices',
];

export const PRESET_NOTIFY_SERVICES = [
  'persistent_notification',
  'email',
  'file',
  'all',
  'telegram',
  'telegram_bot',
  'discord',
  'line',
  'slack',
  'twilio',
  'alexa_media',
  'androidtv',
  'firetv',
  'google_assistant_broadcast',
];

export function buildDeviceTargets() {
  return (notifyDevices || []).map((n) => slug(n));
}

export function getNotifyTargetOptions() {
  const opts = [];

  // 기본 notify.notify
  opts.push(['notify', 'notify']);

  // 커스텀 notify 서비스
  CUSTOM_NOTIFY_TARGETS.forEach((v) => opts.push([v, v]));

  // mobile_app 디바이스들
  const devices = buildDeviceTargets();
  if (devices.length) {
    devices.forEach((v) => opts.push([v, v]));
  } else {
    opts.push(['(no mobile_app devices)', 'notify']);
  }

  // preset 서비스
  PRESET_NOTIFY_SERVICES.forEach((v) => opts.push([v, v]));

  return opts;
}

export const NOTIFY_TEMPLATE_KINDS = [
  ['trigger entity id', 'TRIGGER_ENTITY_ID'],
  ['trigger friendly name', 'TRIGGER_FRIENDLY_NAME'],
  ['trigger new state', 'TRIGGER_NEW_STATE'],
  ['trigger old state', 'TRIGGER_OLD_STATE'],
  ['now()', 'NOW'],
  ['current date', 'DATE'],
  ['current time (HH:MM)', 'TIME_HM'],
  ['weekday name', 'WEEKDAY'],
  ['user name', 'USER_NAME'],
  ['user language', 'USER_LANG'],
  ['user id', 'USER_ID'],
];

/* ============================================================
 * GROUP ACTION OPTIONS (light / cover)
 * ============================================================ */

export const GROUP_ACTION_DOMAINS = [
  ['cover', 'cover'],
  ['light', 'light'],
];

export const GROUP_DOMAIN_TO_SERVICE_OPTIONS = {
  cover: [
    ['open', 'open_cover'],
    ['close', 'close_cover'],
    ['stop', 'stop_cover'],
  ],
  light: [
    ['on', 'turn_on'],
    ['off', 'turn_off'],
  ],
};

export function getDomainEntityOptionsWithPlaceholder(domain) {
  const list = (dummyEntities || []).filter((e) =>
    e.entity_id.startsWith(`${domain}.`)
  );

  const opts = list.map((e) => [
    e.attributes?.friendly_name || e.entity_id,
    e.entity_id,
  ]);

  opts.unshift(['-', '']);
  return opts;
}

export function getGroupEntityOptions() {
  const field = this;
  const block = field?.getSourceBlock?.() || field?.getParent?.();
  const parent = block?.getSurroundParent?.() || block?.parentBlock_;

  let domain = 'light';
  if (parent?.getField?.('DOMAIN')) {
    domain = parent.getFieldValue('DOMAIN') || domain;
  }

  return getDomainEntityOptionsWithPlaceholder(domain);
}

export function getGroupServiceOptionsByDomain(domain) {
  return GROUP_DOMAIN_TO_SERVICE_OPTIONS[domain] || [];
}
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

# ------------------------------------------------------------
# Main
# ------------------------------------------------------------

def main():
    raw = load_states(IN_JSON)
    entities = build_entities(raw)
    notify_devices = build_notify_devices(raw)

    os.makedirs(DATA_DIR, exist_ok=True)

    write_test2_entities_js(OUT_ENTITIES_JS, entities, notify_devices)
    write_test2_options_js(OUT_OPTIONS_JS)

    print("✅ Done!")
    print("  input :", IN_JSON)
    print("  out   :", OUT_ENTITIES_JS)
    print("  out   :", OUT_OPTIONS_JS)
    print(f"  entities exported: {len(entities)}")
    print("  notifyDevices exported:", len(notify_devices))

if __name__ == "__main__":
    main()
