- alias: 'L09 Speaker Playing → Hallway Light On'
  triggers:
    - trigger: state
      entity_id: media_player.living_room_speaker
      to: 'playing'
  actions:
    - action: light.turn_on
      target:
        entity_id: light.hallway_light