- alias: 'L13 Humidity ≥ 50 → Coffee Maker On'
  triggers:
    - trigger: numeric_state
      entity_id: sensor.living_room_humidity
      above: 50
  actions:
    - action: switch.turn_on
      target:
        entity_id: switch.coffee_maker