- alias: Alarm - Low Battery Notification
  id: 'alarm_low_battery_notification'

  triggers:
    - trigger: numeric_state
      entity_id: 
          - sensor.siren_batt
      below: 30
      for:
        hours: 1
        minutes: 0
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  actions:
    - action: notify.USER1_devices
      data:
        message: Alarm {{ trigger.to_state.attributes.friendly_name }} Low Battery

        