import { STATE_DOMAINS, ACTION_DOMAINS } from './data/options.js';

const eventStateBlocks = (STATE_DOMAINS || [])
  .filter((d) => d !== 'sensor')
  .map((domain) => ({ kind: 'block', type: `event_${domain}_state` }));

const conditionStateBlocks = (STATE_DOMAINS || [])
  .map((domain) => ({ kind: 'block', type: `condition_state_${domain}` }));

const actionBlocks = (ACTION_DOMAINS || [])
  .filter((domain) => !['ecobee', 'script', 'python_script', 'mqtt'].includes(domain))
  .map((domain) => ({ kind: 'block', type: `action_${domain}` }));

export const toolbox = {
  kind: 'categoryToolbox',
  contents: [
    {
      kind: 'category',
      name: 'Rule',
      categorystyle: 'rule_category',
      contents: [
        { kind: 'block', type: 'event_action' },
        { kind: 'block', type: 'event_condition_action' },
      ],
    },
    {
      kind: 'category',
      name: 'Event',
      categorystyle: 'event_category',
      contents: [
        { kind: 'label', text: 'Home Assistant' },
        { kind: 'block', type: 'ha_event_homeassistant' },
        { kind: 'label', text: 'Event' },
        { kind: 'block', type: 'ha_event_event' },
        { kind: 'block', type: 'ha_event_kv' },
        { kind: 'block', type: 'ha_event_event_data_call_service' },
        { kind: 'block', type: 'ha_event_service_data_entity_id' },
        { kind: 'block', type: 'ha_event_context_kv' },
        { kind: 'label', text: 'MQTT' },
        { kind: 'block', type: 'ha_event_mqtt' },
        { kind: 'block', type: 'ha_event_mqtt_payload' },
        { kind: 'block', type: 'ha_event_mqtt_value_template' },
        { kind: 'block', type: 'ha_event_mqtt_encoding' },
        { kind: 'label', text: 'State' },
        ...eventStateBlocks,
        { kind: 'label', text: 'Group' },
        { kind: 'block', type: 'event_group_entities' },
        { kind: 'block', type: 'event_group_numeric_entities' },
        { kind: 'block', type: 'event_group_entity_item' },
        { kind: 'block', type: 'event_sensor_numeric_state' },
        { kind: 'label', text: 'Time' },
        { kind: 'block', type: 'ha_event_time_state' },
        { kind: 'block', type: 'ha_event_time_pattern' },
        { kind: 'block', type: 'ha_event_for_hms' },
        { kind: 'label', text: 'Template' },
        { kind: 'block', type: 'ha_event_template' },
        { kind: 'label', text: 'Sun' },
        { kind: 'block', type: 'ha_event_sun' },
        { kind: 'block', type: 'ha_event_offset' },
        { kind: 'block', type: 'ha_event_sun_state' },
      ],
    },
    {
      kind: 'category',
      name: 'Condition',
      categorystyle: 'condition_category',
      contents: [
        { kind: 'label', text: 'Logic' },
        { kind: 'block', type: 'condition_logic' },
        { kind: 'block', type: 'condition_not_value' },
        { kind: 'label', text: 'Template' },
        { kind: 'block', type: 'condition_template' },
        { kind: 'label', text: 'Time' },
        { kind: 'block', type: 'condition_time' },
        { kind: 'block', type: 'condition_time_weekly' },
        { kind: 'label', text: 'Sun' },
        { kind: 'block', type: 'condition_sun' },
        { kind: 'block', type: 'condition_sun_after' },
        { kind: 'block', type: 'condition_sun_before' },
        { kind: 'block', type: 'condition_sun_offset' },
        { kind: 'label', text: 'State' },
        ...conditionStateBlocks,
        { kind: 'label', text: 'Numeric State' },
        { kind: 'block', type: 'condition_numeric_state_entity' },
        { kind: 'block', type: 'condition_numeric_state_attribute' },
        { kind: 'label', text: 'Data' },
        { kind: 'block', type: 'condition_data_attribute' },
        { kind: 'block', type: 'condition_data_state' },
      ],
    },
    {
      kind: 'category',
      name: 'Action',
      categorystyle: 'action_category',
      contents: [
        { kind: 'label', text: 'Action' },
        ...actionBlocks,
        { kind: 'block', type: 'action_ecobee_service' },
        { kind: 'block', type: 'action_script_call' },
        { kind: 'block', type: 'action_script_target_entity' },
        { kind: 'label', text: 'Group' },
        { kind: 'block', type: 'action_group_entities' },
        { kind: 'block', type: 'action_join' },
        { kind: 'block', type: 'action_group_entity_item' },
        { kind: 'label', text: 'MQTT' },
        { kind: 'block', type: 'action_mqtt_publish' },
        { kind: 'block', type: 'action_mqtt_payload_text' },
        { kind: 'block', type: 'action_mqtt_qos' },
        { kind: 'block', type: 'action_mqtt_retain' },
        { kind: 'block', type: 'action_mqtt_evaluate_payload' },
        { kind: 'block', type: 'action_mqtt_data_kv' },
        { kind: 'label', text: 'Data' },
        { kind: 'block', type: 'action_data_brightness_pct' },
        { kind: 'block', type: 'action_data_transition' },
        { kind: 'block', type: 'action_data_color' },
        { kind: 'block', type: 'action_data_effect' },
        { kind: 'block', type: 'action_data_announce' },
        { kind: 'block', type: 'action_data_media_content_type' },
        { kind: 'block', type: 'action_data_climate_preset_mode' },
        { kind: 'block', type: 'action_data_kv_text' },
        { kind: 'label', text: 'Delay' },
        { kind: 'block', type: 'action_delay' },
        { kind: 'label', text: 'Logic' },
        { kind: 'block', type: 'action_if_else' },
        { kind: 'block', type: 'action_if_then' },
        { kind: 'label', text: 'Notify' },
        { kind: 'block', type: 'action_notify' },
        { kind: 'block', type: 'action_notify_message_text' },
        { kind: 'block', type: 'action_notify_message_template' },
        { kind: 'label', text: 'Notify Tag' },
        { kind: 'block', type: 'action_notify_tag' },
        { kind: 'block', type: 'notify_tag' },
        { kind: 'block', type: 'notify_action' },
        { kind: 'block', type: 'notify_prop_title' },
        { kind: 'block', type: 'notify_prop_destructive' },
        { kind: 'block', type: 'notify_prop_activationMode' },
        { kind: 'block', type: 'notify_push_option' },
      ],
    },
  ],
};
